spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/seplagdb
    username: seplag
    password: seplag
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  application:
    name: seplag-backend

minio:
  url: http://64.23.178.251:9000
  access-key: admin
  secret-key: admin123
  bucket: album-covers

server:
  port: 8080
  address: 0.0.0.0
